# Preprocessing Teks

In [15]:
%pip install pandas nltk Sastrawi polars

Requirement already satisfied: pandas in .\env\Lib\site-packages (3.0.6)
Requirement already satisfied: nltk in .\env\Lib\site-packages (3.10.3)
Requirement already satisfied: Sastrawi in .\env\Lib\site-packages (1.0.1)
Requirement already satisfied: polars in .\env\Lib\site-packages (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in .\env\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\env\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\env\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: defusedxml in .\env\Lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in .\env\Lib\site-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in .\env\Lib\site-packages (from nltk) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in .\env\Lib\site-packages (from nltk) (2026.9.29)
Requirement already satisfied: tqdm in .\env\Lib\site-packages (from nltk) (4.70.1)
Requirement already satisfied: polars-runtime-32==2.0.0 in .\env\Lib\site-packages (from polars) (2.0.0)
Requirement already satisfied: six>=1.5 in .\env\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: cloudpickle>=3.0 in .\env\Lib\site-packages (from joblib->nltk) (3.1.2)
Requirement already satisfied: colorama in .\env\Lib\site-packages (from tqdm->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

## Library

In [16]:
import re
import html
import polars as pl
import nltk
# import spacy
import unicodedata
from functools import lru_cache
from collections import Counter

# import pandas as pd

from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [17]:
nltk.download("stopwords")

# Model spaCy untuk bahasa Indonesia
# spacy.cli.download("xx_ent_wiki_sm")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Musa\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

## Helper Fungsion

In [18]:
def to_list(v):
    """map_elements memberi pl.Series untuk kolom list -> ubah ke list Python."""
    if v is None: return []
    if isinstance(v, pl.Series): return v.to_list()
    return list(v)
 
def _apply_str(df, col, out, fn):
    return df.with_columns(pl.col(col).map_elements(fn, return_dtype=pl.Utf8).alias(out))
 
def _apply_list(df, col, out, fn):
    return df.with_columns(
        pl.col(col).map_elements(lambda v: fn(to_list(v)), return_dtype=pl.List(pl.Utf8)).alias(out))

## Dataset

In [19]:
df = pl.read_csv("data_twiter/timnas_final.csv")

In [20]:
df

shape: (12_260, 32)
┌───────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬─────────┐
│ type  ┆ id         ┆ url        ┆ twitterUrl ┆ … ┆ retweeted_ ┆ isConversa ┆ searchTer ┆ isQuote │
│ ---   ┆ ---        ┆ ---        ┆ ---        ┆   ┆ tweet      ┆ tionContro ┆ mIndex    ┆ ---     │
│ str   ┆ i64        ┆ str        ┆ str        ┆   ┆ ---        ┆ lled       ┆ ---       ┆ bool    │
│       ┆            ┆            ┆            ┆   ┆ str        ┆ ---        ┆ i64       ┆         │
│       ┆            ┆            ┆            ┆   ┆            ┆ bool       ┆           ┆         │
╞═══════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═════════╡
│ tweet ┆ 2108135985 ┆ https://x. ┆ https://tw ┆ … ┆ null       ┆ false      ┆ 0         ┆ null    │
│       ┆ 704001818  ┆ com/indozo ┆ itter.com/ ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ nemedia/st ┆ indozoneme ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ …          ┆ …          ┆   ┆            ┆            ┆           ┆         │
│ tweet ┆ 2108133007 ┆ https://x. ┆ https://tw ┆ … ┆ null       ┆ false      ┆ 0         ┆ null    │
│       ┆ 307702498  ┆ com/jawapo ┆ itter.com/ ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ s/status/2 ┆ jawapos/st ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ …          ┆ …          ┆   ┆            ┆            ┆           ┆         │
│ tweet ┆ 2108132172 ┆ https://x. ┆ https://tw ┆ … ┆ null       ┆ false      ┆ 0         ┆ null    │
│       ┆ 431540703  ┆ com/karedd ┆ itter.com/ ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ _/status/2 ┆ karedd_/st ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ …          ┆ …          ┆   ┆            ┆            ┆           ┆         │
│ tweet ┆ 2108128642 ┆ https://x. ┆ https://tw ┆ … ┆ null       ┆ false      ┆ 0         ┆ null    │
│       ┆ 283024777  ┆ com/milyar ┆ itter.com/ ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ derkalcer/ ┆ milyarderk ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ …          ┆ …          ┆   ┆            ┆            ┆           ┆         │
│ tweet ┆ 2108128304 ┆ https://x. ┆ https://tw ┆ … ┆ null       ┆ false      ┆ 0         ┆ null    │
│       ┆ 180195697  ┆ com/sports ┆ itter.com/ ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ kompascom/ ┆ sportskomp ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ …          ┆ …          ┆   ┆            ┆            ┆           ┆         │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …       │
│ tweet ┆ 2107361261 ┆ https://x. ┆ https://tw ┆ … ┆ null       ┆ false      ┆ 3         ┆ null    │
│       ┆ 055021384  ┆ com/ssbmas ┆ itter.com/ ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ mas/status ┆ ssbmasmas/ ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ …          ┆ …          ┆   ┆            ┆            ┆           ┆         │
│ tweet ┆ 2107360723 ┆ https://x. ┆ https://tw ┆ … ┆ null       ┆ false      ┆ 3         ┆ true    │
│       ┆ 806601308  ┆ com/bimo_m ┆ itter.com/ ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ ulyoto/sta ┆ bimo_mulyo ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ …          ┆ …          ┆   ┆            ┆            ┆           ┆         │
│ tweet ┆ 2107360659 ┆ https://x. ┆ https://tw ┆ … ┆ null       ┆ false      ┆ 3         ┆ true    │
│       ┆ 927355712  ┆ com/urekzi ┆ itter.com/ ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ /status/21 ┆ urekzi/sta ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ …          ┆ …          ┆   ┆            ┆            ┆           ┆         │
│ tweet ┆ 2107360111 ┆ https://x. ┆ https://tw ┆ … ┆ null       ┆ false      ┆ 3         ┆ null    │
│       ┆ 731900747  ┆ com/benzjo ┆ itter.com/ ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ e/status/2 ┆ benzjoe/st ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ …          ┆ …          ┆   ┆            ┆            ┆           ┆         │
│ tweet ┆ 2107358852 ┆ https://x. ┆ https://tw ┆ … ┆ null       ┆ false      ┆ 3         ┆ null    │
│       ┆ 211777623  ┆ com/Hendro ┆ itter.com/ ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ 481154/sta ┆ Hendro4811 ┆   ┆            ┆            ┆           ┆         │
│       ┆            ┆ …          ┆ …          ┆   ┆            ┆            ┆           ┆         │
└───────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴─────────┘

In [21]:
df = df.select("text")
df

shape: (12_260, 1)
┌─────────────────────────────────┐
│ text                            │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Elkan Baggott mengaku bangga j… │
│ Pembalap MotoGP Fermin Aldegue… │
│ ngeliat banyaknya reaksi "ajai… │
│ Terpantau hanya akun ini yang … │
│ Baca di sini: https://t.co/fED… │
│ …                               │
│ Apa pun Analisisnya, Mari Raya… │
│ Pantesan dukun Thailand nya ka… │
│ Setuju sih ini, thailand kalah… │
│ @OnefootballM Lihat Thailand, … │
│ Thailand kalah melawan team Er… │
└─────────────────────────────────┘

## Noise Removal

Noise Removal digunakan untuk membersihkan atau menghapus elemen yang biasanya tidak dibutuhkan dalam analisis teks, seperti HTML, URL, alamat email, mention, karakter kontrol, dan spasi berlebih yang tidak relevan dan tidak memiliki nilai informasi untuk analisis teks.

Contoh yang dibersihkan: Tanda baca, emoji, tag HTML, URL, karakter khusus (seperti @, #, $), dan spasi berlebih (whitespace).

### Code

In [22]:
EMOJI = re.compile("[\U0001F300-\U0001FAFF\U00002600-\U000027BF\U0001F1E6-\U0001F1FF\uFE0F\u200d]")

In [23]:
def noise_removal(df, text_col, output_col="text_clean"):
    def clean(text):
        if text is None: return ""
        text = html.unescape(str(text))
        text = re.sub(r"<[^>]+>", " ", text)
        text = re.sub(r"https?://\S+|www\.\S+|\b\w+\.(?:co|com|id)/\S+", " ", text)
        text = re.sub(r"\b[\w.+-]+@[\w.-]+\.[a-zA-Z]{2,}\b", " ", text)
        text = re.sub(r"(?<!\w)@\w+", " ", text)
        text = re.sub(r"^\s*RT\b", " ", text)
        # hashtag: buang '#', pisahkan CamelCase
        text = re.sub(r"#(\w+)", lambda m: " " + re.sub(r"(?<=[a-z])(?=[A-Z])", " ", m.group(1)) + " ", text)
        text = EMOJI.sub(" ", text)
        text = re.sub(r"[\x00-\x1f\x7f]", " ", text)
        return re.sub(r"\s+", " ", text).strip()
    return _apply_str(df, text_col, output_col, clean)
 
ROMAN = re.compile(r"^m{0,3}(cm|cd|d?c{0,3})(xc|xl|l?x{0,3})(ix|iv|v?i{0,3})$")
def _collapse(m):
    w = m.group(0)
    if ROMAN.match(w) or w == "www":      # III, XXX, www jangan diubah
        return w
    return re.sub(r"(\w)\1{2,}", r"\1", w)

In [24]:
df_noise = noise_removal(
    df, text_col="text"
)

In [25]:
df_noise

shape: (12_260, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ text                            ┆ text_clean                      │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ Elkan Baggott mengaku bangga j… ┆ Elkan Baggott mengaku bangga j… │
│ Pembalap MotoGP Fermin Aldegue… ┆ Pembalap MotoGP Fermin Aldegue… │
│ ngeliat banyaknya reaksi "ajai… ┆ ngeliat banyaknya reaksi "ajai… │
│ Terpantau hanya akun ini yang … ┆ Terpantau hanya akun ini yang … │
│ Baca di sini: https://t.co/fED… ┆ Baca di sini: Calvin Verdonk t… │
│ …                               ┆ …                               │
│ Apa pun Analisisnya, Mari Raya… ┆ Apa pun Analisisnya, Mari Raya… │
│ Pantesan dukun Thailand nya ka… ┆ Pantesan dukun Thailand nya ka… │
│ Setuju sih ini, thailand kalah… ┆ Setuju sih ini, thailand kalah… │
│ @OnefootballM Lihat Thailand, … ┆ Lihat Thailand, mereka kalah d… │
│ Thailand kalah melawan team Er… ┆ Thailand kalah melawan team Er… │
└─────────────────────────────────┴─────────────────────────────────┘

In [26]:
print(type(df))

<class 'polars.dataframe.frame.DataFrame'>

## Normalisasi Teks

Normalisasi teks adalah proses menyeragamkan format teks, terutama huruf kapital, Unicode, dan spasi agar memiliki struktur linguistik yang seragam, terutama untuk teks tidak formal, bahasa gaul, singkatan, atau typo (typhographical errors).

Contoh: Mengubah kata "bgt" menjadi "banget", "udh" menjadi "sudah", atau menstandarisasi penulisan angka dan simbol mata uang.

### Code

In [27]:
SLANG = {
    "yg": "yang", "dg": "dengan", "dgn": "dengan", "utk": "untuk", "krn": "karena",
    "karna": "karena", "tdk": "tidak", "gak": "tidak", "ga": "tidak", "nggak": "tidak",
    "gk": "tidak", "enggak": "tidak", "ngga": "tidak", "bkn": "bukan", "bkan": "bukan",
    "sdh": "sudah", "udh": "sudah", "udah": "sudah", "blm": "belum", "jg": "juga",
    "jga": "juga", "sm": "sama", "sma": "sama", "klo": "kalau", "kalo": "kalau",
    "klu": "kalau", "trus": "terus", "tp": "tapi", "tpi": "tapi", "aja": "saja",
    "bgt": "banget", "emg": "memang", "emang": "memang", "org": "orang", "ornag": "orang",
    "gw": "saya", "gue": "saya", "gua": "saya", "lu": "kamu", "loe": "kamu",
    "dr": "dari", "dlm": "dalam", "pd": "pada", "sbg": "sebagai", "spt": "seperti",
    "mknya": "makanya", "pkiran": "pikiran", "stlah": "setelah", "mnjbat": "menjabat",
    "ko": "kok", "mentri": "menteri", "thn": "tahun", "nglantik": "melantik",
    "latarbelakang": "latar belakang", "ehh": "eh", "wajarlah": "wajar lah",
    "rg": "rocky gerung"
}

In [28]:
def text_normalization(df, text_col, output_col="text_normalized", slang=SLANG):
    def norm(text):
        if not text: return ""
        text = unicodedata.normalize("NFKC", text).lower()
        text = re.sub(r"[“”„‟]", '"', text)
        text = re.sub(r"[‘’‚‛]", "'", text)
        text = re.sub(r"[—–]", " - ", text)
        text = re.sub(r"\b\w*(\w)\1{2,}\w*\b", _collapse, text)       # mantaaap -> mantap (angka Romawi dikecualikan)
        text = re.sub(r"\brp\s?(\d)", r"rp \1", text)                # rp76 -> rp 76
        text = re.sub(r"\b([a-z]+)2\b", r"\1-\1", text)             # tiba2 -> tiba-tiba
        text = re.sub(r"\b[a-z0-9]+\b", lambda m: slang.get(m.group(0), m.group(0)), text)
        return re.sub(r"\s+", " ", text).strip()
    return _apply_str(df, text_col, output_col, norm)

In [29]:
df_normalized = text_normalization(
    df_noise, text_col="text_clean"
)

In [30]:
df_normalized

shape: (12_260, 3)
┌────────────────────────────────┬────────────────────────────────┬────────────────────────────────┐
│ text                           ┆ text_clean                     ┆ text_normalized                │
│ ---                            ┆ ---                            ┆ ---                            │
│ str                            ┆ str                            ┆ str                            │
╞════════════════════════════════╪════════════════════════════════╪════════════════════════════════╡
│ Elkan Baggott mengaku bangga   ┆ Elkan Baggott mengaku bangga   ┆ elkan baggott mengaku bangga   │
│ j…                             ┆ j…                             ┆ j…                             │
│ Pembalap MotoGP Fermin         ┆ Pembalap MotoGP Fermin         ┆ pembalap motogp fermin         │
│ Aldegue…                       ┆ Aldegue…                       ┆ aldegue…                       │
│ ngeliat banyaknya reaksi       ┆ ngeliat banyaknya reaksi       ┆ ngeliat banyaknya reaksi       │
│ "ajai…                         ┆ "ajai…                         ┆ "ajai…                         │
│ Terpantau hanya akun ini yang  ┆ Terpantau hanya akun ini yang  ┆ terpantau hanya akun ini yang  │
│ …                              ┆ …                              ┆ …                              │
│ Baca di sini:                  ┆ Baca di sini: Calvin Verdonk   ┆ baca di sini: calvin verdonk   │
│ https://t.co/fED…              ┆ t…                             ┆ t…                             │
│ …                              ┆ …                              ┆ …                              │
│ Apa pun Analisisnya, Mari      ┆ Apa pun Analisisnya, Mari      ┆ apa pun analisisnya, mari      │
│ Raya…                          ┆ Raya…                          ┆ raya…                          │
│ Pantesan dukun Thailand nya    ┆ Pantesan dukun Thailand nya    ┆ pantesan dukun thailand nya    │
│ ka…                            ┆ ka…                            ┆ ka…                            │
│ Setuju sih ini, thailand       ┆ Setuju sih ini, thailand       ┆ setuju sih ini, thailand       │
│ kalah…                         ┆ kalah…                         ┆ kalah…                         │
│ @OnefootballM Lihat Thailand,  ┆ Lihat Thailand, mereka kalah   ┆ lihat thailand, mereka kalah   │
│ …                              ┆ d…                             ┆ d…                             │
│ Thailand kalah melawan team    ┆ Thailand kalah melawan team    ┆ thailand kalah melawan team    │
│ Er…                            ┆ Er…                            ┆ er…                            │
└────────────────────────────────┴────────────────────────────────┴────────────────────────────────┘

## Tokenisasi

Memecah kalimat atau paragraf yang panjang menjadi unit-unit kecil yang disebut token (biasanya berupa kata atau frasa), hasilnya berupa list, bukan string..

Contoh: Kalimat "Saya sedang belajar NLP." dipecah menjadi: ["Saya", "sedang", "belajar", "NLP"].

### Code

In [31]:
# def tokenization(df, text_col, output_col="tokens"):
#     """
#     Memecah teks menjadi token kata.
#     Output setiap baris berupa list.
#     """
#     result = df.clone()

#     def tokenize_text(text):
#         if text is None:
#             return ""
#         # if pl.isna(text):
#         #     return []

#         text = str(text)

#         # Ambil rangkaian karakter alfanumerik.
#         # Kata dengan apostrof atau tanda hubung dipisah.
#         return re.findall(r"\b\w+\b", text, flags=re.UNICODE)

#     return df.with_columns(
#         df[text_col].map_elements(tokenize_text).alias(output_col)
#     )
#     # result[output_col] = result[text_col].apply(tokenize_text)
#     # return result

In [32]:
TOKEN_RE = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")
def tokenization(df, text_col, output_col="tokens"):
    return df.with_columns(
        pl.col(text_col).map_elements(lambda t: TOKEN_RE.findall(t or ""),
                                      return_dtype=pl.List(pl.Utf8)).alias(output_col))

In [33]:
df_tokens = tokenization(
    df_normalized, text_col="text_normalized"
)

In [34]:
df_tokens

shape: (12_260, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ text                   ┆ text_clean             ┆ text_normalized        ┆ tokens                │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ str                    ┆ str                    ┆ str                    ┆ list[str]             │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ Elkan Baggott mengaku  ┆ Elkan Baggott mengaku  ┆ elkan baggott mengaku  ┆ ["elkan", "baggott",  │
│ bangga j…              ┆ bangga j…              ┆ bangga j…              ┆ … "2026"]             │
│ Pembalap MotoGP Fermin ┆ Pembalap MotoGP Fermin ┆ pembalap motogp fermin ┆ ["pembalap",          │
│ Aldegue…               ┆ Aldegue…               ┆ aldegue…               ┆ "motogp", … "sabr…    │
│ ngeliat banyaknya      ┆ ngeliat banyaknya      ┆ ngeliat banyaknya      ┆ ["ngeliat",           │
│ reaksi "ajai…          ┆ reaksi "ajai…          ┆ reaksi "ajai…          ┆ "banyaknya", … "be…   │
│ Terpantau hanya akun   ┆ Terpantau hanya akun   ┆ terpantau hanya akun   ┆ ["terpantau",         │
│ ini yang …             ┆ ini yang …             ┆ ini yang …             ┆ "hanya", … "si"]      │
│ Baca di sini:          ┆ Baca di sini: Calvin   ┆ baca di sini: calvin   ┆ ["baca", "di", …      │
│ https://t.co/fED…      ┆ Verdonk t…             ┆ verdonk t…             ┆ "202610081529…        │
│ …                      ┆ …                      ┆ …                      ┆ …                     │
│ Apa pun Analisisnya,   ┆ Apa pun Analisisnya,   ┆ apa pun analisisnya,   ┆ ["apa", "pun", …      │
│ Mari Raya…             ┆ Mari Raya…             ┆ mari raya…             ┆ "kemudian"]           │
│ Pantesan dukun         ┆ Pantesan dukun         ┆ pantesan dukun         ┆ ["pantesan", "dukun", │
│ Thailand nya ka…       ┆ Thailand nya ka…       ┆ thailand nya ka…       ┆ … "kalah…             │
│ Setuju sih ini,        ┆ Setuju sih ini,        ┆ setuju sih ini,        ┆ ["setuju", "sih", …   │
│ thailand kalah…        ┆ thailand kalah…        ┆ thailand kalah…        ┆ "semalem"]            │
│ @OnefootballM Lihat    ┆ Lihat Thailand, mereka ┆ lihat thailand, mereka ┆ ["lihat", "thailand", │
│ Thailand, …            ┆ kalah d…               ┆ kalah d…               ┆ … "beris…             │
│ Thailand kalah melawan ┆ Thailand kalah melawan ┆ thailand kalah melawan ┆ ["thailand", "kalah", │
│ team Er…               ┆ team Er…               ┆ team er…               ┆ … "berso…             │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

## Stopwords Removal

Menghapus kata-kata umum yang sering muncul dalam suatu bahasa namun memiliki sedikit atau bahkan tidak memiliki makna analitik yang kuat.

Contoh: dan, yang, di, dari, ke, untuk

### Code

In [35]:
# Stopword bahasa Indonesia
stop_words = set(stopwords.words("indonesian"))

# Tambahan stopword
custom_stopwords = {
    "yg", "dg", "dgn", "nya", "sih", "dong",
    "nih", "deh", "aja", "udah", "gak", "nggak"
}

stop_words.update(custom_stopwords)

In [36]:
def build_stopwords(keep_negation=True):
    sw = set(stopwords.words("indonesian"))
    sw |= {"sih", "dong", "nih", "deh", "kok", "lah", "kan", "nya", "tuh", "nah", "yah", "ya"}
    if keep_negation:
        sw -= {"tidak", "bukan", "tak", "belum", "jangan", "tanpa"}
    return sw
 
def stopword_removal(df, text_col, output_col="tokens_no_stopwords", stop_words=None):
    stop_words = stop_words or build_stopwords()
    return _apply_list(df, text_col, output_col,
                       lambda toks: [t for t in toks if t not in stop_words and len(t) > 1])

In [37]:
# stop_words

In [38]:
df_no_stopwords = stopword_removal(
    df_tokens, text_col="tokens"
)

In [39]:
df_no_stopwords

shape: (12_260, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ text              ┆ text_clean        ┆ text_normalized   ┆ tokens            ┆ tokens_no_stopwo │
│ ---               ┆ ---               ┆ ---               ┆ ---               ┆ rds              │
│ str               ┆ str               ┆ str               ┆ list[str]         ┆ ---              │
│                   ┆                   ┆                   ┆                   ┆ list[str]        │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ Elkan Baggott     ┆ Elkan Baggott     ┆ elkan baggott     ┆ ["elkan",         ┆ ["elkan",        │
│ mengaku bangga j… ┆ mengaku bangga j… ┆ mengaku bangga j… ┆ "baggott", …      ┆ "baggott", …     │
│                   ┆                   ┆                   ┆ "2026"]           ┆ "2026"]          │
│ Pembalap MotoGP   ┆ Pembalap MotoGP   ┆ pembalap motogp   ┆ ["pembalap",      ┆ ["pembalap",     │
│ Fermin Aldegue…   ┆ Fermin Aldegue…   ┆ fermin aldegue…   ┆ "motogp", …       ┆ "motogp", …      │
│                   ┆                   ┆                   ┆ "sabr…            ┆ "sabr…           │
│ ngeliat banyaknya ┆ ngeliat banyaknya ┆ ngeliat banyaknya ┆ ["ngeliat",       ┆ ["ngeliat",      │
│ reaksi "ajai…     ┆ reaksi "ajai…     ┆ reaksi "ajai…     ┆ "banyaknya", …    ┆ "banyaknya", …   │
│                   ┆                   ┆                   ┆ "be…              ┆ "ne…             │
│ Terpantau hanya   ┆ Terpantau hanya   ┆ terpantau hanya   ┆ ["terpantau",     ┆ ["terpantau",    │
│ akun ini yang …   ┆ akun ini yang …   ┆ akun ini yang …   ┆ "hanya", … "si"]  ┆ "akun", … "si"]  │
│ Baca di sini:     ┆ Baca di sini:     ┆ baca di sini:     ┆ ["baca", "di", …  ┆ ["baca",         │
│ https://t.co/fED… ┆ Calvin Verdonk t… ┆ calvin verdonk t… ┆ "202610081529…    ┆ "calvin", …      │
│                   ┆                   ┆                   ┆                   ┆ "20261008…       │
│ …                 ┆ …                 ┆ …                 ┆ …                 ┆ …                │
│ Apa pun           ┆ Apa pun           ┆ apa pun           ┆ ["apa", "pun", …  ┆ ["analisisnya",  │
│ Analisisnya, Mari ┆ Analisisnya, Mari ┆ analisisnya, mari ┆ "kemudian"]       ┆ "mari", … "lak…  │
│ Raya…             ┆ Raya…             ┆ raya…             ┆                   ┆                  │
│ Pantesan dukun    ┆ Pantesan dukun    ┆ pantesan dukun    ┆ ["pantesan",      ┆ ["pantesan",     │
│ Thailand nya ka…  ┆ Thailand nya ka…  ┆ thailand nya ka…  ┆ "dukun", …        ┆ "dukun", …       │
│                   ┆                   ┆                   ┆ "kalah…           ┆ "kalah…          │
│ Setuju sih ini,   ┆ Setuju sih ini,   ┆ setuju sih ini,   ┆ ["setuju", "sih", ┆ ["setuju",       │
│ thailand kalah…   ┆ thailand kalah…   ┆ thailand kalah…   ┆ … "semalem"]      ┆ "thailand", …    │
│                   ┆                   ┆                   ┆                   ┆ "sema…           │
│ @OnefootballM     ┆ Lihat Thailand,   ┆ lihat thailand,   ┆ ["lihat",         ┆ ["lihat",        │
│ Lihat Thailand, … ┆ mereka kalah d…   ┆ mereka kalah d…   ┆ "thailand", …     ┆ "thailand", …    │
│                   ┆                   ┆                   ┆ "beris…           ┆ "beris…          │
│ Thailand kalah    ┆ Thailand kalah    ┆ thailand kalah    ┆ ["thailand",      ┆ ["thailand",     │
│ melawan team Er…  ┆ melawan team Er…  ┆ melawan team er…  ┆ "kalah", …        ┆ "kalah", …       │
│                   ┆                   ┆                   ┆ "berso…           ┆ "berso…          │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

In [40]:
df_no_stopwords['tokens_no_stopwords'][6]

shape: (39,)
Series: '' [str]
[
	"baca"
	"calvin"
	"verdonk"
	"tak"
	"merayakan"
	…
	"calvin"
	"verdonk"
	"timnas"
	"indonesia"
	"2026100815292938"
]

## Stemming

Proses memotong imbuhan (prefiks, sufiks, infiks) pada sebuah kata untuk dikembalikan ke bentuk dasarnya (stem), tanpa selalu memperhatikan kaidah kamus yang valid.

Contoh: Kata "memakan", "dimakan", dan "termakan" akan diubah menjadi akar kata dasar "makan".

### Code

In [41]:
# Inisialisasi stemmer bahasa Indonesia
factory = StemmerFactory()
stemmer = factory.create_stemmer()

In [42]:
import polars as pl

def to_list(v):
    """Mengubah pl.Series atau iterables lainnya menjadi list Python."""
    if v is None: 
        return []
    if isinstance(v, pl.Series): 
        return v.to_list()
    if isinstance(v, list):
        return v
    return list(v)

def stemming(df: pl.DataFrame, text_col: str, output_col: str = "tokens_stemmed"):
    """
    Melakukan stemming menggunakan Sastrawi dengan aman dari noise metadata.
    """
    def stem_text(value):
        # Konversi nilai baris (bisa string, list, atau pl.Series) menjadi list token yang bersih
        if value is None:
            tokens = []
        elif isinstance(value, pl.Series):
            tokens = value.to_list()
        elif isinstance(value, list):
            tokens = value
        else:
            # Jika berupa string teks biasa (belum berupa list token)
            tokens = str(value).split()
            
        # Lakukan stemming pada setiap token
        return [stemmer.stem(str(token)) for token in tokens if token is not None]

    return df.with_columns(
        df[text_col].map_elements(
            stem_text,
            return_dtype=pl.List(pl.Utf8)
        ).alias(output_col)
    )

In [43]:
df_stemmed = stemming(
    df_no_stopwords, text_col="tokens_no_stopwords"
)

In [44]:
df_stemmed

shape: (12_260, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ text           ┆ text_clean     ┆ text_normalize ┆ tokens        ┆ tokens_no_sto ┆ tokens_stemme │
│ ---            ┆ ---            ┆ d              ┆ ---           ┆ pwords        ┆ d             │
│ str            ┆ str            ┆ ---            ┆ list[str]     ┆ ---           ┆ ---           │
│                ┆                ┆ str            ┆               ┆ list[str]     ┆ list[str]     │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ Elkan Baggott  ┆ Elkan Baggott  ┆ elkan baggott  ┆ ["elkan",     ┆ ["elkan",     ┆ ["elkan",     │
│ mengaku bangga ┆ mengaku bangga ┆ mengaku bangga ┆ "baggott", …  ┆ "baggott", …  ┆ "baggott", …  │
│ j…             ┆ j…             ┆ j…             ┆ "2026"]       ┆ "2026"]       ┆ "2026"]       │
│ Pembalap       ┆ Pembalap       ┆ pembalap       ┆ ["pembalap",  ┆ ["pembalap",  ┆ ["balap",     │
│ MotoGP Fermin  ┆ MotoGP Fermin  ┆ motogp fermin  ┆ "motogp", …   ┆ "motogp", …   ┆ "motogp", …   │
│ Aldegue…       ┆ Aldegue…       ┆ aldegue…       ┆ "sabr…        ┆ "sabr…        ┆ "sabrina…     │
│ ngeliat        ┆ ngeliat        ┆ ngeliat        ┆ ["ngeliat",   ┆ ["ngeliat",   ┆ ["ngeliat",   │
│ banyaknya      ┆ banyaknya      ┆ banyaknya      ┆ "banyaknya",  ┆ "banyaknya",  ┆ "banyak", …   │
│ reaksi "ajai…  ┆ reaksi "ajai…  ┆ reaksi "ajai…  ┆ … "be…        ┆ … "ne…        ┆ "negar…       │
│ Terpantau      ┆ Terpantau      ┆ terpantau      ┆ ["terpantau", ┆ ["terpantau", ┆ ["pantau",    │
│ hanya akun ini ┆ hanya akun ini ┆ hanya akun ini ┆ "hanya", …    ┆ "akun", …     ┆ "akun", …     │
│ yang …         ┆ yang …         ┆ yang …         ┆ "si"]         ┆ "si"]         ┆ "si"]         │
│ Baca di sini:  ┆ Baca di sini:  ┆ baca di sini:  ┆ ["baca",      ┆ ["baca",      ┆ ["baca",      │
│ https://t.co/f ┆ Calvin Verdonk ┆ calvin verdonk ┆ "di", … "2026 ┆ "calvin", …   ┆ "calvin", …   │
│ ED…            ┆ t…             ┆ t…             ┆ 10081529…     ┆ "20261008…    ┆ "20261008…    │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ Apa pun        ┆ Apa pun        ┆ apa pun        ┆ ["apa",       ┆ ["analisisnya ┆ ["analisis",  │
│ Analisisnya,   ┆ Analisisnya,   ┆ analisisnya,   ┆ "pun", …      ┆ ", "mari", …  ┆ "mari", …     │
│ Mari Raya…     ┆ Mari Raya…     ┆ mari raya…     ┆ "kemudian"]   ┆ "lak…         ┆ "laku"]       │
│ Pantesan dukun ┆ Pantesan dukun ┆ pantesan dukun ┆ ["pantesan",  ┆ ["pantesan",  ┆ ["pantesan",  │
│ Thailand nya   ┆ Thailand nya   ┆ thailand nya   ┆ "dukun", …    ┆ "dukun", …    ┆ "dukun", …    │
│ ka…            ┆ ka…            ┆ ka…            ┆ "kalah…       ┆ "kalah…       ┆ "kalah…       │
│ Setuju sih     ┆ Setuju sih     ┆ setuju sih     ┆ ["setuju",    ┆ ["setuju",    ┆ ["tuju",      │
│ ini, thailand  ┆ ini, thailand  ┆ ini, thailand  ┆ "sih", …      ┆ "thailand", … ┆ "thailand", … │
│ kalah…         ┆ kalah…         ┆ kalah…         ┆ "semalem"]    ┆ "sema…        ┆ "semale…      │
│ @OnefootballM  ┆ Lihat          ┆ lihat          ┆ ["lihat",     ┆ ["lihat",     ┆ ["lihat",     │
│ Lihat          ┆ Thailand,      ┆ thailand,      ┆ "thailand", … ┆ "thailand", … ┆ "thailand", … │
│ Thailand, …    ┆ mereka kalah   ┆ mereka kalah   ┆ "beris…       ┆ "beris…       ┆ "beris…       │
│                ┆ d…             ┆ d…             ┆               ┆               ┆               │
│ Thailand kalah ┆ Thailand kalah ┆ thailand kalah ┆ ["thailand",  ┆ ["thailand",  ┆ ["thailand",  │
│ melawan team   ┆ melawan team   ┆ melawan team   ┆ "kalah", …    ┆ "kalah", …    ┆ "kalah", …    │
│ Er…            ┆ Er…            ┆ er…            ┆ "berso…       ┆ "berso…       ┆ "sorak…       │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [45]:
# STEM_EXCEPTIONS = {"belasan": "belas"}
# PROTECTED = {"wantimpres", "gibran", "prabowo", "rocky", "gerung", "pratikno", "dpr"}

In [46]:
# _stemmer = StemmerFactory().create_stemmer()
# @lru_cache(maxsize=None)
# def _stem(tok):
#     if tok in PROTECTED or tok.isdigit() or "-" in tok: return tok
#     if tok in STEM_EXCEPTIONS: return STEM_EXCEPTIONS[tok]
#     return _stemmer.stem(tok)
    
# def stemming(df, text_col, output_col="tokens_stemmed"):
#     return _apply_list(df, text_col, output_col, lambda toks: [_stem(t) for t in toks])

In [47]:
df_stemmed['tokens_stemmed'][0]

shape: (14,)
Series: '' [str]
[
	"elkan"
	"baggott"
	"aku"
	"bangga"
	"orang"
	…
	"juara"
	"fifa"
	"asean"
	"cup"
	"2026"
]

## Lemmatization

Proses mengubah kata berimbuhan menjadi bentuk dasarnya berdasarkan kamus dan tata bahasa yang valid (lemma), dengan memperhatikan konteks kalimat. Berbeda dengan stemming, proses ini idealnya menghasilkan bentuk lema yang valid secara linguistik.

Isi kamus lemma sebaiknya ditentukan dari kata berimbuhan yang benar-benar sering muncul dari data, bukan contoh umum. aturan untuk menentukan niai lema bisasnya menggunakan beberaoa ruls seperti:
1. Kalau imbuhan hanya mengubah bentuk gramatikal tanpa mengubah makna inti (dilantik → lantik), pakai kata dasar.

2. Kalau kata berimbuhan sudah punya makna sendiri yang berbeda dari kata dasarnya (pemerintah, kebijakan, anggaran, alasan), pertahankan bentuk aslinya sebagai lemma.

### Cek

### Code

In [48]:
# Kamus awal; bisa diperluas sesuai domain
lemma_dictionary = {
    "membaca": "baca",
    "membacakan": "baca",
    "dibaca": "baca",
    "bacaan": "baca",
    "berlari": "lari",
    "berjalan": "jalan",
    "berjualan": "jual",
    "penjualan": "jual",
    "membeli": "beli",
    "pembelian": "beli",
    "menulis": "tulis",
    "penulisan": "tulis",
}

In [49]:

def lemmatization(
    df: pl.DataFrame,
    text_col: str,
    output_col: str = "tokens_lemmatized",
    lemma_dict: dict = None
):
    """
    Lemmatization berbasis kamus.
    Kata yang tidak ada dalam kamus dipertahankan.
    """
    if lemma_dict is None:
        lemma_dict = lemma_dictionary

    def lemmatize_text(value):
        if value is None:
            return []
        # kolom list di Polars masuk sebagai pl.Series -> ubah ke list Python
        if isinstance(value, pl.Series):
            tokens = value.to_list()
        elif isinstance(value, list):
            tokens = value
        else:
            tokens = str(value).split()

        return [lemma_dict.get(str(t).lower(), str(t).lower()) for t in tokens]

    return df.with_columns(
        pl.col(text_col).map_elements(
            lemmatize_text,
            return_dtype=pl.List(pl.Utf8)
        ).alias(output_col)
    )

In [50]:
df_lemmatized = lemmatization(
    df_no_stopwords, text_col="tokens_no_stopwords"
)

In [51]:
df_lemmatized

shape: (12_260, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ text           ┆ text_clean     ┆ text_normalize ┆ tokens        ┆ tokens_no_sto ┆ tokens_lemmat │
│ ---            ┆ ---            ┆ d              ┆ ---           ┆ pwords        ┆ ized          │
│ str            ┆ str            ┆ ---            ┆ list[str]     ┆ ---           ┆ ---           │
│                ┆                ┆ str            ┆               ┆ list[str]     ┆ list[str]     │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ Elkan Baggott  ┆ Elkan Baggott  ┆ elkan baggott  ┆ ["elkan",     ┆ ["elkan",     ┆ ["elkan",     │
│ mengaku bangga ┆ mengaku bangga ┆ mengaku bangga ┆ "baggott", …  ┆ "baggott", …  ┆ "baggott", …  │
│ j…             ┆ j…             ┆ j…             ┆ "2026"]       ┆ "2026"]       ┆ "2026"]       │
│ Pembalap       ┆ Pembalap       ┆ pembalap       ┆ ["pembalap",  ┆ ["pembalap",  ┆ ["pembalap",  │
│ MotoGP Fermin  ┆ MotoGP Fermin  ┆ motogp fermin  ┆ "motogp", …   ┆ "motogp", …   ┆ "motogp", …   │
│ Aldegue…       ┆ Aldegue…       ┆ aldegue…       ┆ "sabr…        ┆ "sabr…        ┆ "sabr…        │
│ ngeliat        ┆ ngeliat        ┆ ngeliat        ┆ ["ngeliat",   ┆ ["ngeliat",   ┆ ["ngeliat",   │
│ banyaknya      ┆ banyaknya      ┆ banyaknya      ┆ "banyaknya",  ┆ "banyaknya",  ┆ "banyaknya",  │
│ reaksi "ajai…  ┆ reaksi "ajai…  ┆ reaksi "ajai…  ┆ … "be…        ┆ … "ne…        ┆ … "ne…        │
│ Terpantau      ┆ Terpantau      ┆ terpantau      ┆ ["terpantau", ┆ ["terpantau", ┆ ["terpantau", │
│ hanya akun ini ┆ hanya akun ini ┆ hanya akun ini ┆ "hanya", …    ┆ "akun", …     ┆ "akun", …     │
│ yang …         ┆ yang …         ┆ yang …         ┆ "si"]         ┆ "si"]         ┆ "si"]         │
│ Baca di sini:  ┆ Baca di sini:  ┆ baca di sini:  ┆ ["baca",      ┆ ["baca",      ┆ ["baca",      │
│ https://t.co/f ┆ Calvin Verdonk ┆ calvin verdonk ┆ "di", … "2026 ┆ "calvin", …   ┆ "calvin", …   │
│ ED…            ┆ t…             ┆ t…             ┆ 10081529…     ┆ "20261008…    ┆ "20261008…    │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ Apa pun        ┆ Apa pun        ┆ apa pun        ┆ ["apa",       ┆ ["analisisnya ┆ ["analisisnya │
│ Analisisnya,   ┆ Analisisnya,   ┆ analisisnya,   ┆ "pun", …      ┆ ", "mari", …  ┆ ", "mari", …  │
│ Mari Raya…     ┆ Mari Raya…     ┆ mari raya…     ┆ "kemudian"]   ┆ "lak…         ┆ "lak…         │
│ Pantesan dukun ┆ Pantesan dukun ┆ pantesan dukun ┆ ["pantesan",  ┆ ["pantesan",  ┆ ["pantesan",  │
│ Thailand nya   ┆ Thailand nya   ┆ thailand nya   ┆ "dukun", …    ┆ "dukun", …    ┆ "dukun", …    │
│ ka…            ┆ ka…            ┆ ka…            ┆ "kalah…       ┆ "kalah…       ┆ "kalah…       │
│ Setuju sih     ┆ Setuju sih     ┆ setuju sih     ┆ ["setuju",    ┆ ["setuju",    ┆ ["setuju",    │
│ ini, thailand  ┆ ini, thailand  ┆ ini, thailand  ┆ "sih", …      ┆ "thailand", … ┆ "thailand", … │
│ kalah…         ┆ kalah…         ┆ kalah…         ┆ "semalem"]    ┆ "sema…        ┆ "sema…        │
│ @OnefootballM  ┆ Lihat          ┆ lihat          ┆ ["lihat",     ┆ ["lihat",     ┆ ["lihat",     │
│ Lihat          ┆ Thailand,      ┆ thailand,      ┆ "thailand", … ┆ "thailand", … ┆ "thailand", … │
│ Thailand, …    ┆ mereka kalah   ┆ mereka kalah   ┆ "beris…       ┆ "beris…       ┆ "beris…       │
│                ┆ d…             ┆ d…             ┆               ┆               ┆               │
│ Thailand kalah ┆ Thailand kalah ┆ thailand kalah ┆ ["thailand",  ┆ ["thailand",  ┆ ["thailand",  │
│ melawan team   ┆ melawan team   ┆ melawan team   ┆ "kalah", …    ┆ "kalah", …    ┆ "kalah", …    │
│ Er…            ┆ Er…            ┆ er…            ┆ "berso…       ┆ "berso…       ┆ "berso…       │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

## Hasil

In [52]:
columns_to_view = [
    "text",
    "text_clean",
    "text_normalized",
    "tokens",
    "tokens_no_stopwords",
    "tokens_stemmed",
    "tokens_lemmatized"
]

df_comparison = (
    df_lemmatized
    .with_columns(df_stemmed["tokens_stemmed"])
    .select(columns_to_view)
)

df_comparison.head()

shape: (5, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ text         ┆ text_clean  ┆ text_normal ┆ tokens      ┆ tokens_no_s ┆ tokens_stem ┆ tokens_lemm │
│ ---          ┆ ---         ┆ ized        ┆ ---         ┆ topwords    ┆ med         ┆ atized      │
│ str          ┆ str         ┆ ---         ┆ list[str]   ┆ ---         ┆ ---         ┆ ---         │
│              ┆             ┆ str         ┆             ┆ list[str]   ┆ list[str]   ┆ list[str]   │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ Elkan        ┆ Elkan       ┆ elkan       ┆ ["elkan",   ┆ ["elkan",   ┆ ["elkan",   ┆ ["elkan",   │
│ Baggott      ┆ Baggott     ┆ baggott     ┆ "baggott",  ┆ "baggott",  ┆ "baggott",  ┆ "baggott",  │
│ mengaku      ┆ mengaku     ┆ mengaku     ┆ … "2026"]   ┆ … "2026"]   ┆ … "2026"]   ┆ … "2026"]   │
│ bangga j…    ┆ bangga j…   ┆ bangga j…   ┆             ┆             ┆             ┆             │
│ Pembalap     ┆ Pembalap    ┆ pembalap    ┆ ["pembalap" ┆ ["pembalap" ┆ ["balap",   ┆ ["pembalap" │
│ MotoGP       ┆ MotoGP      ┆ motogp      ┆ , "motogp", ┆ , "motogp", ┆ "motogp", … ┆ , "motogp", │
│ Fermin       ┆ Fermin      ┆ fermin      ┆ … "sabr…    ┆ … "sabr…    ┆ "sabrina…   ┆ … "sabr…    │
│ Aldegue…     ┆ Aldegue…    ┆ aldegue…    ┆             ┆             ┆             ┆             │
│ ngeliat      ┆ ngeliat     ┆ ngeliat     ┆ ["ngeliat", ┆ ["ngeliat", ┆ ["ngeliat", ┆ ["ngeliat", │
│ banyaknya    ┆ banyaknya   ┆ banyaknya   ┆ "banyaknya" ┆ "banyaknya" ┆ "banyak", … ┆ "banyaknya" │
│ reaksi       ┆ reaksi      ┆ reaksi      ┆ , … "be…    ┆ , … "ne…    ┆ "negar…     ┆ , … "ne…    │
│ "ajai…       ┆ "ajai…      ┆ "ajai…      ┆             ┆             ┆             ┆             │
│ Terpantau    ┆ Terpantau   ┆ terpantau   ┆ ["terpantau ┆ ["terpantau ┆ ["pantau",  ┆ ["terpantau │
│ hanya akun   ┆ hanya akun  ┆ hanya akun  ┆ ", "hanya", ┆ ", "akun",  ┆ "akun", …   ┆ ", "akun",  │
│ ini yang …   ┆ ini yang …  ┆ ini yang …  ┆ … "si"]     ┆ … "si"]     ┆ "si"]       ┆ … "si"]     │
│ Baca di      ┆ Baca di     ┆ baca di     ┆ ["baca",    ┆ ["baca",    ┆ ["baca",    ┆ ["baca",    │
│ sini: https: ┆ sini:       ┆ sini:       ┆ "di", … "20 ┆ "calvin", … ┆ "calvin", … ┆ "calvin", … │
│ //t.co/fED…  ┆ Calvin      ┆ calvin      ┆ 2610081529… ┆ "20261008…  ┆ "20261008…  ┆ "20261008…  │
│              ┆ Verdonk t…  ┆ verdonk t…  ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [53]:
df_export = df_comparison.clone()

token_columns = [
    "tokens",
    "tokens_no_stopwords",
    "tokens_stemmed",
    "tokens_lemmatized"
]

# Ubah list token menjadi string
for col in token_columns:
    df_export = df_export.with_columns(
        df_export[col].map_elements(
            lambda tokens: " ".join(tokens) if isinstance(tokens, list) else str(tokens),
            return_dtype=pl.Utf8
        ).alias(col)
    )

# # Simpan hasil ke CSV
# df_export.write_csv(
#     "hasil_preprocessing.csv",
#     encoding="utf8"   # Polars tidak pakai "utf-8-sig", cukup "utf8"
# )

In [54]:
df_export = df_comparison.with_columns(
    [pl.col(c).list.join(" ") for c in token_columns]
)

df_export.write_csv("hasil_preprocessing2.csv")

In [55]:
df_export.write_csv("hasil_preprocessing2.csv")

In [56]:
df_load = pl.read_csv('hasil_preprocessing2.csv')

In [57]:
df_load

shape: (12_260, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ text         ┆ text_clean  ┆ text_normal ┆ tokens      ┆ tokens_no_s ┆ tokens_stem ┆ tokens_lemm │
│ ---          ┆ ---         ┆ ized        ┆ ---         ┆ topwords    ┆ med         ┆ atized      │
│ str          ┆ str         ┆ ---         ┆ str         ┆ ---         ┆ ---         ┆ ---         │
│              ┆             ┆ str         ┆             ┆ str         ┆ str         ┆ str         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ Elkan        ┆ Elkan       ┆ elkan       ┆ elkan       ┆ elkan       ┆ elkan       ┆ elkan       │
│ Baggott      ┆ Baggott     ┆ baggott     ┆ baggott     ┆ baggott     ┆ baggott aku ┆ baggott     │
│ mengaku      ┆ mengaku     ┆ mengaku     ┆ mengaku     ┆ mengaku     ┆ bangga      ┆ mengaku     │
│ bangga j…    ┆ bangga j…   ┆ bangga j…   ┆ bangga j…   ┆ bangga o…   ┆ orang…      ┆ bangga o…   │
│ Pembalap     ┆ Pembalap    ┆ pembalap    ┆ pembalap    ┆ pembalap    ┆ balap       ┆ pembalap    │
│ MotoGP       ┆ MotoGP      ┆ motogp      ┆ motogp      ┆ motogp      ┆ motogp      ┆ motogp      │
│ Fermin       ┆ Fermin      ┆ fermin      ┆ fermin      ┆ fermin      ┆ fermin      ┆ fermin      │
│ Aldegue…     ┆ Aldegue…    ┆ aldegue…    ┆ aldegue…    ┆ aldegue…    ┆ aldeguer r… ┆ aldegue…    │
│ ngeliat      ┆ ngeliat     ┆ ngeliat     ┆ ngeliat     ┆ ngeliat     ┆ ngeliat     ┆ ngeliat     │
│ banyaknya    ┆ banyaknya   ┆ banyaknya   ┆ banyaknya   ┆ banyaknya   ┆ banyak      ┆ banyaknya   │
│ reaksi       ┆ reaksi      ┆ reaksi      ┆ reaksi      ┆ reaksi      ┆ reaksi      ┆ reaksi      │
│ "ajai…       ┆ "ajai…      ┆ "ajai…      ┆ ajaib…      ┆ ajaib…      ┆ ajaib or…   ┆ ajaib…      │
│ Terpantau    ┆ Terpantau   ┆ terpantau   ┆ terpantau   ┆ terpantau   ┆ pantau akun ┆ terpantau   │
│ hanya akun   ┆ hanya akun  ┆ hanya akun  ┆ hanya akun  ┆ akun tidak  ┆ tidak       ┆ akun tidak  │
│ ini yang …   ┆ ini yang …  ┆ ini yang …  ┆ ini yang …  ┆ reaksi ti…  ┆ reaksi      ┆ reaksi ti…  │
│              ┆             ┆             ┆             ┆             ┆ timna…      ┆             │
│ Baca di      ┆ Baca di     ┆ baca di     ┆ baca di     ┆ baca calvin ┆ baca calvin ┆ baca calvin │
│ sini: https: ┆ sini:       ┆ sini:       ┆ sini calvin ┆ verdonk tak ┆ verdonk tak ┆ verdonk tak │
│ //t.co/fED…  ┆ Calvin      ┆ calvin      ┆ verdonk ta… ┆ meraya…     ┆ raya h…     ┆ meraya…     │
│              ┆ Verdonk t…  ┆ verdonk t…  ┆             ┆             ┆             ┆             │
│ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           │
│ Apa pun      ┆ Apa pun Ana ┆ apa pun ana ┆ apa pun     ┆ analisisnya ┆ analisis    ┆ analisisnya │
│ Analisisnya, ┆ lisisnya,   ┆ lisisnya,   ┆ analisisnya ┆ mari        ┆ mari raya   ┆ mari        │
│ Mari Raya…   ┆ Mari Raya…  ┆ mari raya…  ┆ mari rayak… ┆ rayakan     ┆ indonesia   ┆ rayakan     │
│              ┆             ┆             ┆             ┆ indon…      ┆ b…          ┆ indon…      │
│ Pantesan     ┆ Pantesan    ┆ pantesan    ┆ pantesan    ┆ pantesan    ┆ pantesan    ┆ pantesan    │
│ dukun        ┆ dukun       ┆ dukun       ┆ dukun       ┆ dukun       ┆ dukun       ┆ dukun       │
│ Thailand nya ┆ Thailand    ┆ thailand    ┆ thailand    ┆ thailand    ┆ thailand    ┆ thailand    │
│ ka…          ┆ nya ka…     ┆ nya ka…     ┆ nya ka…     ┆ kalah       ┆ kalah       ┆ kalah       │
│ Setuju sih   ┆ Setuju sih  ┆ setuju sih  ┆ setuju sih  ┆ setuju      ┆ tuju        ┆ setuju      │
│ ini,         ┆ ini,        ┆ ini,        ┆ ini         ┆ thailand    ┆ thailand    ┆ thailand    │
│ thailand     ┆ thailand    ┆ thailand    ┆ thailand    ┆ kalah       ┆ kalah       ┆ kalah       │
│ kalah…       ┆ kalah…      ┆ kalah…      ┆ kalah …     ┆ terhorma…   ┆ hormat sal… ┆ terhorma…   │
│ @Onefootball ┆ Lihat       ┆ lihat       ┆ lihat       ┆ lihat       ┆ lihat       ┆ lihat       │
│ M Lihat      ┆ Thailand,   ┆ thailand,   ┆ thailand    ┆ thailand    ┆ thailand    ┆ thailand    │
│ Thailand, …  ┆ mereka      ┆ mereka      ┆ mereka      ┆ kalah final ┆ kalah final ┆ kalah final │
│              ┆ kalah d…    ┆ kalah d…    ┆ kalah di…   ┆ tid…        ┆ tid…        ┆ tid…        │
│ Thailand     ┆ Thailand    ┆ thailand    ┆ thailand    ┆ thailand    ┆ thailand    ┆ thailand    │
│ kalah        ┆ kalah       ┆ kalah       ┆ kalah       ┆ kalah       ┆ kalah lawan ┆ kalah       │
│ melawan team ┆ melawan     ┆ melawan     ┆ melawan     ┆ melawan     ┆ team ered…  ┆ melawan     │
│ Er…          ┆ team Er…    ┆ team er…    ┆ team er…    ┆ team er…    ┆             ┆ team er…    │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘